#!/bin/bash
set -euo pipefail

# ============================================================================
# ZAP Automation Framework Runner
#
# Executes a ZAP scan using the Automation Framework with the appropriate
# plan (baseline or full) against the specified target URL.
#
# Environment variables:
#   TARGET_URL  - URL to scan (required)
#   SCAN_TYPE   - "baseline" or "full" (default: baseline)
#   FAIL_ON     - Alert level that causes failure: High, Medium, Low, Informational
#   CONTEXT_FILE - Optional path to a custom ZAP context file
# ============================================================================

readonly PLANS_DIR="zap-pipelines/tasks/zap-scan/plans"
readonly REPORTS_DIR="reports"
readonly WORK_DIR="/zap/wrk"

# --- Validation ---

if [[ -z "${TARGET_URL:-}" ]]; then
    echo "ERROR: TARGET_URL is required but not set."
    echo "Usage: Set TARGET_URL to the URL of the application to scan."
    exit 1
fi

SCAN_TYPE="${SCAN_TYPE:-baseline}"
if [[ "${SCAN_TYPE}" != "baseline" && "${SCAN_TYPE}" != "full" ]]; then
    echo "ERROR: SCAN_TYPE must be 'baseline' or 'full', got '${SCAN_TYPE}'."
    exit 1
fi

FAIL_ON="${FAIL_ON:-High}"
case "${FAIL_ON}" in
    High|Medium|Low|Informational) ;;
    *)
        echo "ERROR: FAIL_ON must be High, Medium, Low, or Informational, got '${FAIL_ON}'."
        exit 1
        ;;
esac

echo "========================================="
echo "ZAP Security Scan"
echo "========================================="
echo "Target URL:  ${TARGET_URL}"
echo "Scan type:   ${SCAN_TYPE}"
echo "Fail on:     ${FAIL_ON} or higher"
echo "ZAP version: $(zap.sh -version 2>/dev/null || echo 'unknown')"
echo "========================================="
echo ""

# --- Prepare automation plan ---

PLAN_SOURCE="${PLANS_DIR}/${SCAN_TYPE}.yaml"

if [[ ! -f "${PLAN_SOURCE}" ]]; then
    echo "ERROR: Automation plan not found at '${PLAN_SOURCE}'."
    exit 1
fi

# Create working directory for ZAP
mkdir -p "${WORK_DIR}/reports"
mkdir -p "${REPORTS_DIR}"

# Substitute TARGET_URL and FAIL_ON into the plan
PLAN_FILE="${WORK_DIR}/plan.yaml"
sed \
    -e "s|\${TARGET_URL}|${TARGET_URL}|g" \
    -e "s|\${FAIL_ON}|${FAIL_ON}|g" \
    "${PLAN_SOURCE}" > "${PLAN_FILE}"

echo "Automation plan prepared: ${PLAN_FILE}"
echo ""

# --- Run ZAP ---

echo "Starting ZAP scan..."
echo ""

ZAP_EXIT_CODE=0
zap.sh -cmd -autorun "${PLAN_FILE}" || ZAP_EXIT_CODE=$?

echo ""
echo "========================================="
echo "ZAP exited with code: ${ZAP_EXIT_CODE}"
echo "========================================="

# --- Collect reports ---

echo ""
echo "Collecting reports..."

# Copy any reports generated by ZAP to the output directory
if ls "${WORK_DIR}"/reports/* 1>/dev/null 2>&1; then
    cp "${WORK_DIR}"/reports/* "${REPORTS_DIR}/"
    echo "Reports saved to ${REPORTS_DIR}/:"
    ls -la "${REPORTS_DIR}/"
else
    echo "WARNING: No reports were generated."
fi

# --- Interpret exit code ---

echo ""
case ${ZAP_EXIT_CODE} in
    0)
        echo "RESULT: PASS - No alerts at or above '${FAIL_ON}' level."
        ;;
    1)
        echo "RESULT: ERROR - ZAP encountered an error during the scan."
        echo "Check the output above for details."
        exit 1
        ;;
    2)
        echo "RESULT: FAIL - Alerts found at or above '${FAIL_ON}' level."
        echo "Review the reports in the build artifacts for details."
        exit 1
        ;;
    *)
        echo "RESULT: UNKNOWN - Unexpected exit code ${ZAP_EXIT_CODE}."
        exit 1
        ;;
esac

echo ""
echo "Scan complete."
